### ISSUE TITLE
Bundle archives no longer have a top level directory

### ISSUE THREAD

**Issue by hseeberger** [sbt/sbt-bundle#21]
Thanks to https://github.com/sbt/sbt-native-packager/issues/276 :-(

**Comment by muuki88** [comment]
You should be able to configure this. [By default top-level directories](https://github.com/sbt/sbt-native-packager/commit/2c39fc4e3981789faee13673596f472c320f1df4#diff-0d27e6843c96a31bcc8c17973f84cebfR68) should be like they were before the change.

Do you have a small example to reproduce the error?

**Comment by hseeberger** [comment]
Self-made issue: https://github.com/sbt/sbt-bundle/blob/master/src/main/scala/com/typesafe/sbt/bundle/SbtBundle.scala#L134

**Comment by muuki88** [comment]
Ah, okay. Shouldn't be to hard to fix :)

**Comment by hseeberger** [comment]
No, but writing a test for it is pretty hard ;-)

**Comment by muuki88** [comment]
[Here is a test](https://github.com/sbt/sbt-native-packager/tree/master/src/sbt-test/universal/staging-custom-main) checking the contents of a zip (probably you already know)

**Comment by huntc** [comment]
Ah, so that what was what that param was for. :-P
