### ISSUE TITLE
Fix invalid JVM heap options

### ISSUE THREAD

**Issue by hseeberger** [sbt/sbt-bundle#23]
- Minimum is given via -Xms, not -Xmm
- Minimum and maximum must not have an equals sign, i.e. not -Xmx=1024, but -Xmx1024
- The launcher created with the sbt-native-packager needs -X options prefixed with -J, .e.g -J-Xmx1024

**Comment by huntc** [comment]
I'm really sorry for the poor quality here.

**Comment by hseeberger** [comment]
Don't worry, I learned a lot ;-)
