### ISSUE TITLE
Web app dev experience

### ISSUE THREAD

**Issue by huntc** [sbt/sbt-bundle#29]
Play applications are not prepared to live on a context path by default, and so most developers assume that their application will not share a port with other web applications. This situation is probably compounded by the one VM/one app approach which is quite prevalent in our industry. As ConductR allows many http apps to share the same port, only to be further distinguished by the path, sbt-bundle creates a services configuration in respect of that e.g.:

```
    endpoints        = {
      "angular-seed-play" = {
        protocol  = "http"
        bind-port = 0
        services  = ["http:/angular-seed-play"]
      }
    }
```

The user of the above service will then access the Play app at `http://x.x.x.x:9000/angular-seed-play/` which may not be intuitive for them. Furthermore if the developer uses Play's Redirect function and does not specify an `application.context` property then redirects will fail (`/angular-seed-play` will be dropped).

The proposal here is to change the configuration approach so that ports are used to distinguish http apps. Thus, the above `services` declaration becomes:

```
    endpoints  = {
      "angular-seed-play" = {
        protocol  = "http"
        bind-port = 0
        services  = ["http:"]
      }
    }
```

...and the app is addressed at `http://x.x.x.x:9000`.

During development, a dev's app appearing at port 9000 will be sufficient and on par with how things work today for them. However when it comes to an operator deploying the application, the operator must be allowed to override the services configuration.

The proposal is to allow the operator to provide an alternate `bundle.conf` file with their configuration. This new `bundle.conf` does not have to be complete and will be used to overlay the developer's. For example to override the endpoint configuration, the entire contents of the file could be just:

```
endpoints."angular-seed-play".services = ["http:/angular-seed-play"]
```

When a configuration is supplied with a bundle as part of `conduct load`, the `shazar`d configuration archive can presently represent a single file OR a directory of files. These scenarios are both supported presently. In the case of a directory, the first file found is used. ConductR will be changed so that any `bundle.conf` is filtered out from the list of files.

**Comment by huntc** [comment]
@markusjura This one is for you! Can you please review the idea?

**Comment by markusjura** [comment]
@huntc Sure, will do it on Monday :-)

**Comment by huntc** [comment]
@jroper Your thoughts are always appreciated as well.

**Comment by hseeberger** [comment]
Our default port for http is 80 and for https 443, not 9000.

**Comment by huntc** [comment]
I've not changed any logic - port 9000 was assumed I think...

**Comment by jroper** [comment]
By the way, this is one reason why I was so interested in routing by the host header - webapps sharing a port is actually very common (https://jazzy.id.au actually serves 3 different websites on the one port, one of them is a Play website, and none of them have to do anything special to share a port) and sharing ports has been done almost since the dawn of the web (at least since HTTP/1.1 became mainstream, this is when the Host header became compulsory), it's just that the way they've shared ports has been to distinguish by host, not path.

**Comment by huntc** [comment]
Description updated as a result of design discussions.

**Comment by markusjura** [comment]
I like the new approach. Checked the README and looks fine for me as well.

**Comment by hseeberger** [comment]
For the record: we don't support routing by the host header yet.

**Comment by huntc** [comment]
We need to support routing by host header: that's one of the use cases that got us started. Would it be tricky to get this done as a priority? Sounds like a beta 1 requirement. Wdyt?

**Comment by huntc** [comment]
(That's "got us started" with the migration away from Python)
