### ISSUE TITLE
Improve Endpoint DSL or make ConductRs quickstart explain the magic 0

### ISSUE THREAD

**Issue by ktoso** [sbt/sbt-bundle#33]
The `0` in `Endpoint` is a magic number, when first using ConductR, I'd go through the quickstart. The quickstart is using it but not explaining it. This should be explained in the Quickstart - 1 sentence, or better: the DSL should be improved to convey this info.

When I see something like "port -> port" instincts from other tools kick in and I say "oh yeah 9000 -> 9000", which is wrong.

It's typed DSL so it could be made something meaningful instead of 0. With conversions from int to this meaningful type. As in `Endpoint(DynamicallyAllocated, ...)`

**Comment by huntc** [comment]
Another option: introduce an apply function that excludes the bind port. This function should be encouraged over the existing one.

**Comment by huntc** [comment]
Update: Let's go with the structure that allows the bind port to be excluded i.e.:

```scala
  case class Endpoint(protocol: String, bindPort: Int = 0, services: Set[URI])
```

**Comment by hseeberger** [comment]
Parameters with default values should go last, else one must use named arguments.

**Comment by huntc** [comment]
Another option:

case class Endpoint(binding:URI, services:Set[URI])

This way we can capture both the protocol and port optionally as per services. In addition this will provide a path to more flexible proxying where a path can be bound as per a recent requirement:

Endpoint(URI("http://:0/conductr"), Set(URI("http://conductr.typesafe.com")))

WDYT? I think a 0 in this context could be reasonable, or perhaps even the default, thus:

Endpoint(URI("/conductr"), Set(URI("http://conductr.typesafe.com")))

**Comment by huntc** [comment]
That all said, I'm also happy with the changes you made re naming the services param. I think that works.

**Comment by hseeberger** [comment]
Great, then let's keep it that way.

**Comment by huntc** [comment]
Hmm. I'm still troubled by this one. I think we now need a default protocol:

```scala
  case class Endpoint(protocol: String = "http", bindPort: Int = 0, services: Set[URI])
```

...as I'm thinking that it looks weird specifying a bind protocol and not specifying a bind port.

Perhaps `protocol` should also be renamed to `bindProtocol`.

WDYT?

**Comment by hseeberger** [comment]
A default protocol is totally confusing! Why should HTTP be the default? There's no such thing like dynamic protocol allocation. On the other hand there's a very good reason to have `0` as the default for the port, because of dynamic port allocation.

Let's keep things like they are.

**Comment by ktoso** [comment]
Agree with @hseeberger - default port makes sense, protocol may well be "very often http" but I wouldn't default it. Let the user pick.

**Comment by huntc** [comment]
OK, I'm convinced - thanks for the conversation. Good to "talk" these things through.

How about renaming `protocol` to `bindProtocol` though?

**Comment by hseeberger** [comment]
Yeah, that's a good idea. I'll create a ticket.

**Comment by hseeberger** [comment]
See #37.
