### ISSUE TITLE
Enhance check command configuration

### ISSUE THREAD

**Issue by huntc** [sbt/sbt-bundle#49]
Provide a setting for the check command's `--initial-delay` parameter. This parameter controls how many seconds to wait until the check command checks anything.

Also document that a check command may have the following declaration:

```scala
    BundleKeys.checks := Seq(uri("$ES_INTERNAL_HOST?retry-count=10&retry-delay=3")),
```

The accepted params are: 

* "retry-count=<int>" -  number of retries;
* "retry-delay=<int>" - delay in seconds between retries; and
* "docker-timeout=<int>" - timeout in seconds for docker container start

**Comment by markusjura** [comment]
I've looked into [SbtBundle.scala](https://github.com/sbt/sbt-bundle/blob/master/src/main/scala/com/typesafe/sbt/bundle/SbtBundle.scala) and [check.py](https://github.com/typesafehub/conductr/blob/master/check-command/src/main/python/typesafe_conductr/check.py). But I am still a bit confused how to add the `--initial-delay` parameter to the `BundleKeys.checks` command. How does the user specify this setting in the `build.sbt`?
- As a checks argument: `BundleKeys.checks := Seq(uri("$ES_INTERNAL_HOST?retry-count=10&retry-delay=3&initialDelay=5"))` OR
- With a separate BundleKeys command: `BundleKeys.initialDelay := 5s` OR
- Somehow else

> The accepted params are:
> 
>"retry-count=" - number of retries;
>"retry-delay=" - delay in seconds between retries; and
>"docker-timeout=" - timeout in seconds for docker container start

This needs to be only documented in the `README.md` or should we add validation in the [SbtBundle.scala](https://github.com/sbt/sbt-bundle/blob/master/src/main/scala/com/typesafe/sbt/bundle/SbtBundle.scala) as well?
