### ISSUE TITLE
The task configuration:dist generates an invalid bundle.conf

### ISSUE THREAD

**Issue by fsat** [sbt/sbt-bundle#56]
When creating a bundle containing custom configuration without `bundle.conf`, running `sbt configuration:dist` will result in an invalid `bundle.conf` being generated, e.g.

```
version              = "1.1.0"
compatibilityVersion = "0"
components = {
  conductr-haproxy = {
  }
}
```

Please refer to https://github.com/typesafehub/conductr/pull/1011#issuecomment-171184269 for more details on this issue.

**Comment by huntc** [comment]
@fsat can this be closed?

**Comment by markusjura** [comment]
@fsat Ping: Can this be closed. If so we can remove the `bundle.conf` from https://github.com/typesafehub/conductr/blob/master/conductr-haproxy/src/bundle-configuration/conductr-haproxy-dev-mode/bundle.conf

**Comment by fsat** [comment]
@markusjura - Yes, this can be closed. PR is raised to remove the no longer used `bundle.conf`: https://github.com/typesafehub/conductr/pull/1565

cc @huntc
