### ISSUE TITLE
ConductR 1.2: Deprecating or not allowing services

### ISSUE THREAD

**Issue by markusjura** [sbt/sbt-bundle#64]
With ConductR 1.2 we can specify endpoints as ACLs instead services. The current implementation supports already ACLs in the `bundleConfVersion` 1.2.0. In 1.2.0 we can additionally to the ACLs also declare `services`.

@huntc: The question is whether both ACLs and services can be declared in `1.2.0` or we do not allow to declare `services` in 1.2.0 anymore? If the latter one is the case then we need to change the validation in `sbt-bundle` accordingly.

**Comment by huntc** [comment]
We should continue to support `services` for some time. We will deprecate it once 1.2 is released.

**Comment by markusjura** [comment]
Ok, then the current implementation is correct. I'll close this issue therefore.
